name: Insights

# When client modify table data file in db dir
on:
  workflow_dispatch: # manually trigger pipeline
  schedule:
    - cron: '0 0 * * *' # every day at 00:00 UTC

jobs:
  # Create insights for db table
  insights-db-table:
    name: Insights db table
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all history so that git log can get all history

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      # - name: Merge records
      #   run: npx @db-man/cli merge

      - name: Generate insights
        run: |
          git --no-pager log --follow --numstat --pretty="%H %ad" --date=short -- db_files_dir/iam/users.data.json > db_files_dir/iam/users.insights.gitlog
          # check status
          git status
          git diff

      - name: Commit files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # if there is no change, no need to commit
          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "[CI] Generate git log for table"
          fi

      - name: Push changes
        uses: ad-m/github-push-action@master
        # when multiple jobs run at the same time, only last git push will sucess, then other pipelines will fail and send email.
        # to prevent get lots of email notification, use `continue-on-error` to make pipeline success even the git push failed.
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
