name: Insights

# When client modify table data file in db dir
on:
  workflow_dispatch: # manually trigger pipeline
  schedule:
    - cron: '0 0 * * *' # every day at 00:00 UTC

jobs:
  call-reusable-workflow:
    uses: db-man/db-man/.github/workflows/reusable-workflow.yml@main