name: Merge records to table

# when multiple jobs run at the same time, first N pipelines will be cancelled, this may send lots of email (cannot turn off)
# concurrency:
#   group: ${{ github.ref }} # github.ref="refs/heads/main"

# When client modify table data file in db dir
on:
  workflow_dispatch: # manually trigger pipeline
  push: # When client modify table record files in table dir
    paths:
      - '*/*/*/*.json' # dbs/iam/users/123.json

jobs:
  call-merge-reusable-workflow:
    uses: db-man/db-man/.github/workflows/merge-reusable-workflow.yml@main