name: Merge records to table

# when multiple jobs run at the same time, first N pipelines will be cancelled, this may send lots of email (cannot turn off)
# concurrency:
#   group: ${{ github.ref }} # github.ref="refs/heads/main"

# When client modify table data file in db dir
on:
  workflow_dispatch: # manually trigger pipeline
  push: # When client modify table record files in table dir
    paths:
      - '*/*/*/*.json' # dbs/iam/users/123.json

jobs:
  # Merge record data file to whole table data file
  merge-records:
    name: Merge records into table file (table file is modified, repo is dirty now)
    runs-on: ubuntu-latest

    # concurrency:
    #   group: merge
    #   cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2 # `git diff-tree` (used in `@db-man/cli mergeUpdatedTables`) need to compare HEAD and HEAD~1, so need to fetch 2 commits

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x          

      - name: Merge records
        run: npx @db-man/cli mergeUpdatedTables $GITHUB_SHA

      - name: git status
        run: |
          git status
          git diff
          # git pull # this will make sure local update to date

      - name: Commit files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git status
          git add .
          git status
          git commit -m "[CI] Merge records to table"

      - name: Push changes
        uses: ad-m/github-push-action@master
        # when multiple jobs run at the same time, only last git push will sucess, then other pipelines will fail and send email.
        # to prevent get lots of email notification, use `continue-on-error` to make pipeline success even the git push failed.
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
