name: Split table file to records

# when multiple jobs run at the same time, first N pipelines will be cancelled, this may send lots of email (cannot turn off)
# concurrency:
#   group: ${{ github.ref }} # github.ref="refs/heads/main"

# When client modify table data file in db dir
on:
  workflow_dispatch: # manually trigger pipeline
  push: # When client modify table data file in db dir
    paths:
      - "*/*/*.data.json" # dbs/iam/users.data.json

jobs:
  call-split-reusable-workflow:
    uses: db-man/db-man/.github/workflows/split-reusable-workflow.yml@main
